from utils.utils import *

cipher = 'EMGLOSUDCGDNCUSWYSFHNSFCYKDPUMLWGYICOXYSIPJCKQPKUGKMGOLICGINCGACKSNISACYKZSCKXECJCKSHYSXCGOIDPKZCNKSHICGIWYGKKGKGOLDSILKGOIUSIGLEDSPWZUGFZCCNDGYYSFUSZCNXEOJNCGYEOWEUPXEZGACGNFGLKNSACIGOIYCKXCJUCIUZCFZCCNDGYYSFEUEKUZCSOCFZCCNCIACZEJNCSHFZEJZEGMXCYHCJUMGKUCY'

freq = calc_freq_norm(cipher)
print(freq)
word_freq = calc_word_freq(cipher)
print(word_freq)
cipher = cipher.replace('C', 'e')
cipher = cipher.replace('F', 'w')
cipher = cipher.replace('Z', 'h')
cipher = cipher.replace('N', 'l')
cipher = cipher.replace('U', 't')
cipher = cipher.replace('S', 'o')
cipher = cipher.replace('O', 'n')
cipher = cipher.replace('G', 'a')
cipher = cipher.replace('E', 'i')
cipher = cipher.replace('K', 's')
cipher = cipher.replace('M', 'm')
cipher = cipher.replace('L', 'y')
cipher = cipher.replace('Y', 'r')
cipher = cipher.replace('J', 'c')
cipher = cipher.replace('X', 'p')
cipher = cipher.replace('H', 'f')
cipher = cipher.replace('A', 'v')
cipher = cipher.replace('W', 'g')
cipher = cipher.replace('D', 'b')
cipher = cipher.replace('P', 'u')
cipher = cipher.replace('I', 'd')
word_freq = calc_word_freq(cipher)
print(word_freq)
print(cipher)
